### ISSUE TITLE
大佬，代码能学习下吗 没看到代码

### ISSUE THREAD

**Issue by hecheng64** [Liyanhao1209/ZhouYiLLM#1]
大佬，代码能学习下吗 没看到代码

**Comment by Liyanhao1209** [comment]
看到你在csdn的评论了，所有代码都仍然是开源的。你看到的主分支里面是空的，只有一个readme，说明了各个其他分支下的代码的作用。这里并没有把最终大模型微调后产生的文件放进来（因为太大了20+G），放的是处理数据、整形以及最终应用的代码，如果你想用这套去微调一个大模型，我们当时使用的华为Model Link去做的，这个他们在gitee上有官方仓库介绍如何使用他们的库。

**Comment by hecheng64** [comment]
不好意思，没注意其他分支
